"""Smoke test for RVC (Retrieval-based Voice Conversion).

RVC is voice-conversion, not TTS: it ingests source speech and re-renders it in
a target voice's timbre. This smoke uses chatterbox.wav (generated by the
Chatterbox smoke) as the source clip and a Japanese female RVC v2 voice model
(`V2-AISO-HOWATTO.pth`) as the target.

Setup expectations (created out-of-band, see notes/install-gotchas.md):
  - specialized/rvc/assets/hubert/hubert_base.pt        (~190 MB, from lj1995/VoiceConversionWebUI)
  - specialized/rvc/assets/weights/V2-AISO-HOWATTO.pth  (~55 MB, from aa444rt/...)

We use `f0_method='pm'` to avoid the rmvpe.pt download (and rmvpe-on-CUDA-fp16
matmul wedges on some torch versions anyway). Quality of pm is fine for smoke.
"""
import logging
import os
import sys
import time
from pathlib import Path

import soundfile as sf
import torch

# torch 2.6+ defaults torch.load to weights_only=True, which rejects fairseq's
# hubert checkpoint (contains pickled fairseq.data.dictionary.Dictionary). We
# trust these files (downloaded from lj1995 + aa444rt). Monkey-patch back to
# the pre-2.6 default. Same trick we used for XTTS-v2 — see install-gotchas.md.
_orig_torch_load = torch.load
def _torch_load_unsafe(*args, **kwargs):
    kwargs.setdefault("weights_only", False)
    return _orig_torch_load(*args, **kwargs)
torch.load = _torch_load_unsafe

# Paths
RVC_DIR = Path(__file__).resolve().parent.parent.parent / "specialized" / "rvc"
SOURCE_PATH = Path(__file__).resolve().parent.parent / "outputs" / "smoke" / "chatterbox.wav"
OUTPUT_PATH = Path(__file__).resolve().parent.parent / "outputs" / "smoke" / "rvc.wav"
MODEL_NAME = "V2-AISO-HOWATTO.pth"  # lives in assets/weights/

# RVC reads many paths via os.getenv (.env) and relative paths like
# "assets/hubert/hubert_base.pt" and "configs/inuse/...". The repo only works
# if cwd == repo root, so chdir before importing config/VC.
os.chdir(RVC_DIR)
sys.path.insert(0, str(RVC_DIR))

# .env populates weight_root / rmvpe_root / index_root, all relative to cwd.
from dotenv import load_dotenv
load_dotenv(RVC_DIR / ".env")

# Config() uses argparse on sys.argv — strip our own args first.
sys.argv = sys.argv[:1]

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"device={device}  torch={torch.__version__}", flush=True)
if device != "cuda":
    print("ERROR: CUDA required — smoke fails loudly on CPU.", flush=True)
    sys.exit(1)
print(f"gpu={torch.cuda.get_device_name(0)}", flush=True)

# Verify required model files exist before we waste time importing the world.
hubert_path = RVC_DIR / "assets" / "hubert" / "hubert_base.pt"
weight_path = RVC_DIR / "assets" / "weights" / MODEL_NAME
for p in (hubert_path, weight_path, SOURCE_PATH):
    if not p.exists():
        print(f"ERROR: missing required file {p}", flush=True)
        sys.exit(1)

t0 = time.time()
from configs.config import Config
from infer.modules.vc.modules import VC

config = Config()
config.device = "cuda:0"
# is_half is auto-decided by Config.device_config(); on a 5090 it'll be True.
vc = VC(config)
vc.get_vc(MODEL_NAME)
t_load = time.time() - t0
print(f"loaded RVC + voice model ({MODEL_NAME}) in {t_load:.1f}s  tgt_sr={vc.tgt_sr}  version={vc.version}  if_f0={vc.if_f0}", flush=True)

# Source duration (for RTF). load_audio inside the pipeline resamples to 16k,
# so duration in seconds is what we want against the wall-clock conversion time.
src_audio, src_sr = sf.read(str(SOURCE_PATH))
src_duration = src_audio.shape[0] / src_sr
print(f"source: {SOURCE_PATH.name}  sr={src_sr}  dur={src_duration:.2f}s", flush=True)

t0 = time.time()
info, (out_sr, wav_opt) = vc.vc_single(
    0,                       # speaker id (ignored for single-speaker models)
    str(SOURCE_PATH),        # input audio path
    0,                       # f0_up_key: no transpose
    None,                    # f0_file
    "pm",                    # f0_method: pm = parselmouth, lightest, no extra weights
    "",                      # file_index (no retrieval index)
    None,                    # file_index2
    0.0,                     # index_rate (irrelevant w/o index)
    3,                       # filter_radius
    0,                       # resample_sr (0 = keep model's sr)
    0.25,                    # rms_mix_rate
    0.33,                    # protect (consonants)
)
t_conv = time.time() - t0

if wav_opt is None:
    print("ERROR: conversion returned no audio. Info follows:", flush=True)
    print(info, flush=True)
    sys.exit(1)

OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
sf.write(str(OUTPUT_PATH), wav_opt, out_sr)

out_duration = len(wav_opt) / out_sr
rtf = t_conv / src_duration
print(f"converted in {t_conv:.2f}s  src={src_duration:.2f}s  out={out_duration:.2f}s  RTF={rtf:.2f}  (RTF vs source)", flush=True)
print(f"wrote {OUTPUT_PATH} (sr={out_sr}, {OUTPUT_PATH.stat().st_size} bytes)", flush=True)
print(f"pipeline info:\n{info}", flush=True)
sys.exit(0)
